// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourcePlusCircleSvg = &fyne.StaticResource{
	StaticName: "plus-circle.svg",
	StaticContent: []byte(
		"<svg style=\"width:24px;height:24px\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\">\n    <path d=\"M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z\" />\n</svg>"),
}
